name: cov-support
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.74
  - iqtree<2
  - mafft
  - minimap2
  - pip=19.3.1
  - python=3.6
  - r-base=3.5.1
  - r-stringr
  - r-ggplot2
  - r-cowplot
  - snakemake-minimal=5.13
  - pip:
    - pandas==1.0.1
    - pytools==2020.1
    - dendropy>=4.4.0
    - git+https://github.com/cov-ert/datafunk.git

